### PR TITLE
Handle non-fully-active documents

### LINKED ISSUE #218: Handle documents not being fully active
Given a nested content (iframe), it's possible to capture a click event, have the click event remove the iframe, and then call one of the methods.

https://github.com/marcoscaceres/playground/blob/83a28912a59b6f87cec4627536450eaf1a5db8a5/share-parent.html#L6-L18

Accessible from:
https://marcoscaceres.github.io/playground/share-parent.html

In Safari, `.share()` rejects with a `TypeError`.
in Firefox, `.share()` rejects with a `NS_ERROR_UNEXPECTED` ([Gecko code](https://searchfox.org/mozilla-central/source/dom/base/Navigator.cpp#1368-1372)).
In Chrome, `share()` rejects with `NotAllowedError`: "Must be handling a user gesture to perform a share request."

Not sure why Chrome thinks that the click handler is not happening inside a user gesture (technically, not incorrect as the iframe has been removed, but still a weird).

I think we should align align with Safari here and just reject with a TypeError. @saschanaz, wdyt?

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #218 

For *normative* changes, the following tasks have been completed:

 * [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/30417)

Implementation commitment:

 * [ ] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=230088)
 * [ ] [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1246237)
 * [ ] [Gecko](https://phabricator.services.mozilla.com/D90834)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/pull/219.html" title="Last updated on Sep 9, 2021, 7:54 PM UTC (6884cce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-share/219/3bc95bf...6884cce.html" title="Last updated on Sep 9, 2021, 7:54 PM UTC (6884cce)">Diff</a>

### CODE REVIEW

**Comment by ewilligers** [comment]
Thank you for the work on this.

**Review by ewilligers — APPROVED** [review]

**Review by saschanaz — APPROVED** [review]
👍 that was quick

**Comment by marcoscaceres** [comment]
Filed WebKit bug + sending patch.

Updated Gecko's patch for canShare() https://phabricator.services.mozilla.com/D90834

**Comment by marcoscaceres** [comment]
Tests are up at https://github.com/w3c/web-share/pull/219

**Review by saschanaz — APPROVED** [review]
👍 with InvalidStateError.

**Pull request merged**
